package view;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Emberek;
import static model.FajlBeolvas.beolvas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author odor.norbert
 */
public class DolgozokGui extends javax.swing.JFrame {

    public DolgozokGui() {
        initComponents();
    }

    int osszKor = 0;
    int legIdosebb = Integer.MIN_VALUE;
    boolean hatEveDolgozo = false;
    String hatEveDolgozoNeve = "";
    String kivalasztottNem = "";

    /**
     * Creates new form DolgozokGui
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lanyComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        fiuComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lanyRadio = new javax.swing.JRadioButton();
        fiuRadio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        osszKorLabel = new javax.swing.JLabel();
        legIdosebbLabel = new javax.swing.JLabel();
        hatEveDolgozoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lányok");

        lanyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Válassz--" }));
        lanyComboBox.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lanyComboBoxComponentAdded(evt);
            }
        });
        lanyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanyComboBoxActionPerformed(evt);
            }
        });
        ArrayList<Emberek> adatok = null;
        try {
            adatok = beolvas();
        } catch (IOException ex) {
            Logger.getLogger(DolgozokGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Emberek ember : adatok) {
            if (ember.getNeme().equals("L")) {
                lanyComboBox.addItem(ember.getNev());
            }
        }

        jLabel2.setText("Fiúk");

        fiuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Válassz--" }));
        fiuComboBox.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                fiuComboBoxComponentAdded(evt);
            }
        });
        fiuComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiuComboBoxActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(lanyRadio);
        lanyRadio.setText("lány");
        lanyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanyRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(fiuRadio);
        fiuRadio.setText("fiú");
        fiuRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiuRadioActionPerformed(evt);
            }
        });

        jLabel3.setText("Összesítő");

        jLabel5.setText("összes kor:");

        jLabel4.setText("legidősebb:");

        jLabel6.setText("6 éve dolgozó:");

        osszKorLabel.setText(" ");

        legIdosebbLabel.setText(" ");

        hatEveDolgozoLabel.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(osszKorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hatEveDolgozoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lanyRadio)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fiuRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(legIdosebbLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanyRadio)
                    .addComponent(fiuRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(legIdosebbLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(osszKorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hatEveDolgozoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Ment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Adatok");

        jCheckBox1.setText("Mindkettő nem");

        jLabel8.setText("kor:");

        jLabel9.setText("mióta dolgozik:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lanyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fiuComboBox, 0, 122, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lanyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fiuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lanyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanyRadioActionPerformed
        ArrayList<Emberek> adatok = null;
        try {
            adatok = beolvas();
        } catch (IOException ex) {
            Logger.getLogger(DolgozokGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (isEnabled()) {
            osszKor = 0;
            legIdosebb = Integer.MIN_VALUE;
            hatEveDolgozo = false;
            hatEveDolgozoNeve = "";
            kivalasztottNem = "";
            kivalasztottNem = "Lányok";
            for (Emberek ember : adatok) {
                if (ember.getNeme().equals("L")) {
                    osszKor += ember.getKor();
                    if (ember.getKor() > legIdosebb) {
                        legIdosebb = ember.getKor();
                    }
                    if (ember.getMunkTöltÉv() >= 6) {
                        hatEveDolgozo = true;
                        hatEveDolgozoNeve = ember.getNev();
                    }
                }
            }
        }
        hatEveDolgozoLabel.setText(hatEveDolgozo ? hatEveDolgozoNeve : "nincs");
        legIdosebbLabel.setText(String.valueOf(legIdosebb));
        osszKorLabel.setText(String.valueOf(osszKor));
    }//GEN-LAST:event_lanyRadioActionPerformed

    private void fiuRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiuRadioActionPerformed

        ArrayList<Emberek> adatok = null;
        try {
            adatok = beolvas();
        } catch (IOException ex) {
            Logger.getLogger(DolgozokGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (isEnabled()) {
            osszKor = 0;
            legIdosebb = Integer.MIN_VALUE;
            hatEveDolgozo = false;
            hatEveDolgozoNeve = "";
            kivalasztottNem = "";
            kivalasztottNem = "Fiúk";
            for (Emberek ember : adatok) {
                if (ember.getNeme().equals("F")) {
                    osszKor += ember.getKor();
                    if (ember.getKor() > legIdosebb) {
                        legIdosebb = ember.getKor();
                    }
                    if (ember.getMunkTöltÉv() >= 6) {
                        hatEveDolgozo = true;
                        hatEveDolgozoNeve = ember.getNev();
                    }
                }
            }
        }
        hatEveDolgozoLabel.setText(hatEveDolgozo ? hatEveDolgozoNeve : "nincs");
        legIdosebbLabel.setText(String.valueOf(legIdosebb));
        osszKorLabel.setText(String.valueOf(osszKor));
    }//GEN-LAST:event_fiuRadioActionPerformed

    private void lanyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanyComboBoxActionPerformed

    }//GEN-LAST:event_lanyComboBoxActionPerformed

    private void lanyComboBoxComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lanyComboBoxComponentAdded
        ArrayList<Emberek> adatok = null;
        try {
            adatok = beolvas();
        } catch (IOException ex) {
            Logger.getLogger(DolgozokGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Emberek ember : adatok) {
            if (ember.getNeme().equals("L")) {
                lanyComboBox.addItem(ember.getNev());
            }
        }
    }//GEN-LAST:event_lanyComboBoxComponentAdded

    private void fiuComboBoxComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_fiuComboBoxComponentAdded
        ArrayList<Emberek> adatok = null;
        try {
            adatok = beolvas();
        } catch (IOException ex) {
            Logger.getLogger(DolgozokGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Emberek ember : adatok) {
            if (ember.getNeme().equals("F")) {
                fiuComboBox.addItem(ember.getNev());
            }
        }
    }//GEN-LAST:event_fiuComboBoxComponentAdded

    private void fiuComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiuComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiuComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String kiirandoAdatok = kivalasztottNem + ":\nLegidősebb: " + legIdosebb + "\nösszes kor: " + osszKor + "\n6 éve dolgozó: " + hatEveDolgozoNeve;

        try {
            FileWriter myWriter = new FileWriter("dolgozok.txt");
            myWriter.write(kiirandoAdatok);
            myWriter.close();
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DolgozokGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DolgozokGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DolgozokGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DolgozokGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DolgozokGui().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> fiuComboBox;
    private javax.swing.JRadioButton fiuRadio;
    private javax.swing.JLabel hatEveDolgozoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lanyComboBox;
    private javax.swing.JRadioButton lanyRadio;
    private javax.swing.JLabel legIdosebbLabel;
    private javax.swing.JLabel osszKorLabel;
    // End of variables declaration//GEN-END:variables
}
